spring:
  application:
    name: ms-usuarios
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gpatri_usuarios}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 0
springdoc:
  swagger-ui:
    enabled: true
    path: /usuarios/v3/swagger-ui.html
  api-docs:
    enabled: true
    path: /usuarios/v3/docs
    version: openapi_3_1
  writer-with-order-by-keys: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka:eureka@localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
app:
  module-name: Usuarios
  api-version: 1.0
  jwtSecret: ${JWT_SECRET:FbaKFoxbDpfzHGpKjAALXPesF2aiO3WjL3A4meBifE64jdvwUiegpHbDlUkXvekrkXvFVtRLidi7fq7MwqHsCmNFSIff6pCGlfu4Ie3UHa9yNoOyVDbmPqEiX5qM1Z3YzhDXfyrKbppvCYuwDXbfPCkVa45aYCbGX2x9ogZd22zxpoTHHYpImpkJUGo9IXl5DscgPLpdEdRowSkC8hdSYYRD3zu04g5ZRGESelVhqeGTIPEnssJOCaZdcyAR2frs}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
  cors:
    enabled: ${CORS_ENABLED:true}
    allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:8080}