spring:
  application:
    name: ms-eureka
  security:
    user:
      name: eureka
      password: eureka
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/