spring:
  application:
    name: ms-emprestimos
  datasource:
    url: jdbc:postgresql://localhost:5432/gpatri_patrimonios
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
springdoc:
  swagger-ui:
    enabled: true
    path: /docs.html
  api-docs:
    enabled: true
    path: /docs
    version: openapi_3_1
  writer-with-order-by-keys: true
app:
  module-name: Patrimonio
  api-version: 1.0
  jwtSecret: FbaKFoxbDpfzHGpKjAALXPesF2aiO3WjL3A4meBifE64jdvwUiegpHbDlUkXvekrkXvFVtRLidi7fq7MwqHsCmNFSIff6pCGlfu4Ie3UHa9yNoOyVDbmPqEiX5qM1Z3YzhDXfyrKbppvCYuwDXbfPCkVa45aYCbGX2x9ogZd22zxpoTHHYpImpkJUGo9IXl5DscgPLpdEdRowSkC8hdSYYRD3zu04g5ZRGESelVhqeGTIPEnssJOCaZdcyAR2frs