spring:
  application:
    name: ms-emprestimos
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
springdoc:
  swagger-ui:
    enabled: true
    path: /docs.html
  api-docs:
    enabled: true
    path: /docs
    version: openapi_3_1
  writer-with-order-by-keys: true
