package br.edu.ifg.numbers.gpatri.msusuarios.domain.enums;

public enum PermissaoEnum {

    CADASTRAR_USUARIO,
    EDITAR_USUARIO,
    EXCLUIR_USUARIO,
    VISUALIZAR_USUARIO,
    LISTAR_USUARIO,

    CADASTRAR_CARGO,
    EDITAR_CARGO,
    EXCLUIR_CARGO,
    LISTAR_CARGOS,
    VISUALIZAR_CARGO,
    ATRIBUIR_CARGO,

    SOLICITAR_EMPRESTIMO,
    VISUALIZAR_EMPRESTIMO,
    LIBERAR_EMPRESTIMO,
    DELETAR_EMPRESTIMO,
    ATUALIZAR_EMPRESTIMO,
    ATUALIZAR_TODOS_EMPRESTIMOS,
    DELETAR_TODOS_EMPRESTIMOS,
    VISUALIZAR_TODOS_EMPRESTIMOS,

    CADASTRAR_ITEM_PATRIMONIO,
    EDITAR_ITEM_PATRIMONIO,
    EXCLUIR_ITEM_PATRIMONIO,
    LISTAR_ITEM_PATRIMONIO,

    CADASTRAR_PATRIMONIO,
    EDITAR_PATRIMONIO,
    EXCLUIR_PATRIMONIO,
    LISTAR_PATRIMONIO,

    CADASTRAR_CATEGORIA,
    EDITAR_CATEGORIA,
    EXCLUIR_CATEGORIA,
    LISTAR_CATEGORIA,

    CADASTRAR_SITUACAO,
    EDITAR_SITUACAO,
    EXCLUIR_SITUACAO,
    LISTAR_SITUACAO

}
